# Generated by Django 4.2.13 on 2026-06-08 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Admin Login'), ('logout', 'Admin Logout'), ('login_failed', 'Login Failed'), ('ticket_create', 'Ticket Created'), ('ticket_delete', 'Ticket Deleted'), ('ticket_view', 'Ticket Viewed'), ('registration_view', 'Registration Viewed'), ('payment_created', 'Payment Order Created'), ('payment_verified', 'Payment Verified'), ('payment_failed', 'Payment Failed')], max_length=50)),
                ('target', models.CharField(blank=True, max_length=300)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor', 'timestamp'], name='activity_ac_actor_i_43b92c_idx'), models.Index(fields=['action'], name='activity_ac_action_0385c4_idx')],
            },
        ),
    ]
