# Generated by Django 4.2.13 on 2026-06-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Admin Login'), ('logout', 'Admin Logout'), ('login_failed', 'Login Failed'), ('user_registered', 'User Registered'), ('ticket_create', 'Ticket Created'), ('ticket_update', 'Ticket Updated'), ('ticket_delete', 'Ticket Deleted'), ('payment_created', 'Payment Order Created'), ('payment_verified', 'Payment Verified'), ('payment_failed', 'Payment Failed'), ('registration_expired', 'Registration Expired')], max_length=50),
        ),
    ]
