# Generated by Django 4.2.13 on 2026-06-08 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_name', models.CharField(max_length=200)),
                ('attendee_email', models.EmailField(max_length=254)),
                ('attendee_phone', models.CharField(blank=True, max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='registrations.registration')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_items', to='tickets.ticket')),
            ],
            options={
                'indexes': [models.Index(fields=['attendee_email'], name='registratio_attende_93c21c_idx'), models.Index(fields=['ticket'], name='registratio_ticket__ca7c84_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['contact_email'], name='registratio_contact_db08e2_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['status'], name='registratio_status_42419d_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['created_at'], name='registratio_created_a226d9_idx'),
        ),
    ]
