# Generated by Django 4.2.13 on 2026-06-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank',
            field=models.CharField(blank=True, help_text='Bank code, e.g. HDFC, SBIN', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_issuer',
            field=models.CharField(blank=True, help_text='Issuing bank, e.g. HDFC, ICICI', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_last4',
            field=models.CharField(blank=True, help_text='Last 4 digits of the card', max_length=4),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_name',
            field=models.CharField(blank=True, help_text='Cardholder name as on card', max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_network',
            field=models.CharField(blank=True, help_text='e.g. Visa, MasterCard, RuPay, Amex', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_type',
            field=models.CharField(blank=True, help_text='credit or debit', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='error_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='error_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Card'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet'), ('upi', 'UPI'), ('emi', 'EMI')], help_text='Payment method used: card, netbanking, wallet, upi, emi', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='razorpay_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Razorpay processing fee (₹)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='razorpay_tax',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GST on Razorpay fee (₹)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vpa',
            field=models.CharField(blank=True, help_text='UPI VPA / address', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.CharField(blank=True, help_text='Wallet name, e.g. Paytm, PhonePe', max_length=50),
        ),
    ]
