# Generated by Django 4.2.13 on 2026-06-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ticket_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_type', models.CharField(choices=[('limited', 'Limited'), ('unlimited', 'Unlimited')], max_length=10)),
                ('total_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('duplicate_email', models.BooleanField(default=False, help_text='Allow the same email to register multiple times for this ticket')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='tickets_tic_is_acti_a7c054_idx')],
            },
        ),
    ]
